import { createHash } from 'node:crypto';
import { analyze, factLabel, routeTo } from '../../packages/domain/engine';
import { failureById } from '../../packages/domain/fixture';
import type { Blueprint } from '../../packages/domain/model';
import type { Session } from '../../packages/domain/session';
import { summarizeExercise } from '../../packages/domain/debrief';
import { readinessTasks } from '../../packages/domain/readiness';
export const escapeHtml = (s: string) =>
  s.replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!,
  );
export function exportPlan(b: Blueprint, failureId: string) {
  const a = analyze(b, failureById(failureId));
  const list = (items: string[]) =>
    `<ul>${items.map((x) => `<li>${escapeHtml(x)}</li>`).join('')}</ul>`;
  const route = routeTo('work.trusted', a, b).filter((r) => r.kind === 'action');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(b.name)} — recovery plan</title><style>body{font:16px/1.65 system-ui,sans-serif;max-width:850px;margin:50px auto;padding:0 25px;color:#182327}h1{font-size:38px;line-height:1.1}h2{border-top:1px solid #ccc;padding-top:25px;margin-top:35px}small{color:#52606a}table{border-collapse:collapse;width:100%}td,th{text-align:left;vertical-align:top;border-bottom:1px solid #ddd;padding:10px}strong{color:#a73825}.note{padding:18px;background:#f3f4f4}li{margin-bottom:8px}@media print{body{margin:0;font-size:11pt}h2,h3{break-after:avoid}tr,li,.note{break-inside:avoid}}</style></head><body><small>BLACKOUT PROTOCOL / OFFLINE REFERENCE / MODEL v${b.version}</small><h1>${escapeHtml(b.name)}<br>Recovery action plan</h1><p>${escapeHtml(a.failure.label)} · Exported ${new Date().toISOString().slice(0, 10)}</p><div class="note"><strong>Fictional exercise and documented model.</strong> This plan describes recovery arrangements; it does not configure a provider or contain actual recovery secrets. Confirm and test real provider procedures separately.</div><h2>Essential activities</h2><table><thead><tr><th>Activity</th><th>Under this failure</th></tr></thead><tbody>${a.targets.map((t) => `<tr><td>${escapeHtml(t.label)}</td><td>${t.reachable ? (t.confirmed ? 'Route exists in the documented fixture/tested inputs' : 'Route relies on user-reported assumptions') : t.uncertain ? 'Needs confirmation' : 'No route found in this model'}</td></tr>`).join('')}</tbody></table><h2>Recovery sequence</h2>${route.length ? `<ol>${route.map((r) => `<li><b>${escapeHtml(r.label)}</b><br>Owner: ${escapeHtml(r.responsibleRole ?? 'Administrator')}<br>Requires: ${r.requiresAll.map((f) => escapeHtml(factLabel(f, b))).join(', ')}<br><small>${escapeHtml(r.sourceNote)} · Evidence: ${escapeHtml(r.evidence)}</small></li>`).join('')}</ol>` : '<p>No documented independent route currently reaches trusted work access. Assign an owner to confirm an independent method. External provider support remains an unresolved dependency.</p>'}<h2>Owners and recovery resources</h2><table><thead><tr><th>Resource</th><th>Owner</th><th>Notes</th></tr></thead><tbody>${b.resources.map((r) => `<tr><td>${escapeHtml(r.label)}</td><td>${escapeHtml(r.owner)}</td><td>${escapeHtml(r.description)}</td></tr>`).join('')}</tbody></table><h2>Assumptions to confirm</h2>${list(b.assumptions)}<h2>Follow-up actions</h2><table><thead><tr><th>Action / owner</th><th>Status and review</th></tr></thead><tbody>${readinessTasks(
    b,
  )
    .map(
      (t) =>
        `<tr><td>${escapeHtml(t.title)}<br><small>Owner: ${escapeHtml(t.owner)}</small></td><td>${escapeHtml(t.status)} · ${escapeHtml(t.reviewDate || 'Review not scheduled')}<br>${escapeHtml(t.note || 'Outcome not yet recorded')}</td></tr>`,
    )
    .join(
      '',
    )}</tbody></table><h2>Next review</h2><p>Owner: ____________________ Date: ____________________</p><p>Practice outcome and changes: __________________________________________________</p><small>Generated by BLACKOUT PROTOCOL. Keep this document with an authorised custodian. No network connection is needed to read it.</small></body></html>`;
}
export function exportTranscript(s: Session) {
  const content = JSON.stringify(
    {
      schema: 'blackout-transcript-1',
      engineVersion: s.engineVersion,
      scenarioVersion: s.scenarioVersion,
      sessionId: s.id,
      blueprintVersion: s.blueprint.version,
      blueprint: s.blueprint,
      failure: s.failure ?? failureById('work-lockout'),
      mode: s.mode ?? 'story',
      seed: s.seed,
      phase: s.phase,
      startedAt: s.startedAt,
      endedAt: s.endedAt,
      events: s.events,
      roles: s.customRoles ?? [],
      outcome: summarizeExercise(s),
      finalFacts: s.facts,
      paymentDecision: s.paymentDecision ?? 'unresolved',
    },
    null,
    2,
  );
  return { content, sha256: createHash('sha256').update(content).digest('hex') };
}
